FROM quay.io/toolbx/ubuntu-toolbox:25.04

ARG FLAVOR=unsloth

RUN mkdir -p /opt/strix-rocm-all/files

COPY *.sh *.patch Makefile \
    /opt/strix-rocm-all

COPY files/* /opt/strix-rocm-all/files/

WORKDIR /opt/strix-rocm-all

# RUN find .

RUN ./01-install-packages.sh NO_CACHING \
    && make $FLAVOR \
    && make clean \
    && cp files/99-toolbox-banner.sh /etc/profile.d/ \
    && chmod 0644 /etc/profile.d/99-toolbox-banner.sh 

# Banner script (runs on login). Use a high sort key so it runs after venv.sh and 01-rocm-env...
COPY files/99-toolbox-banner.sh /etc/profile.d/99-toolbox-banner.sh
RUN chmod 0644 /etc/profile.d/99-toolbox-banner.sh

# Disable core dumps in interactive shells (helps with recovering faster from ROCm crashes)
RUN printf 'ulimit -S -c 0\n' > /etc/profile.d/90-nocoredump.sh && chmod 0644 /etc/profile.d/90-nocoredump.sh

CMD ["/bin/bash"]

